Revert "build & test & push (machine true, attach workspace)"
This reverts commit 5476b2f6ac74945d7277a43e14d4cf656c2cb190.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,62 +1,35 @@
 version: 2.1
-
-orbs:
-  docker: circleci/docker@1.5.0
-
 jobs:
   build:
+    working_directory: ~/app
     docker:
       - image: cimg/base:2022.09
     steps:
       - checkout
-      - docker/build:
-          image: my-node-app
-          tag: latest
-      - persist_to_workspace:
-          root: .
-          paths:
-            - my-node-app.tar.gz
-
-  test:
-    docker:
-      - image: cimg/base:2022.09
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
+      - setup_remote_docker:
+          docker_layer_caching: true
       - run:
-          name: Load Docker image
+          name: Build Docker image
           command: |
-            gunzip -c ./my-node-app.tar.gz | docker load
+            TAG=0.1.$CIRCLE_BUILD_NUM
+            docker build -t $DOCKERHUB_USERNAME/circleci-new-docker-example:$TAG .
       - run:
           name: Run Docker container
           command: |
-            docker run -d -p 8080:8080 --name my-node-app my-node-app
+            TAG=0.1.$CIRCLE_BUILD_NUM
+            docker run -d -p 8080:8080 --name myapp_container $DOCKERHUB_USERNAME/circleci-new-docker-example:$TAG
       - run:
           name: Test Docker container
           command: |
-            sleep 10  # Attendre que le conteneur démarre
-            curl --fail http://localhost:8080/ || (docker logs my-node-app && exit 1)
-
-  push:
-    docker:
-      - image: cimg/base:2022.09
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - docker/push:
-          image: my-node-app
-          tag: latest
-
-workflows:
-  version: 2
-  build-and-test:
-    jobs:
-      - build
-      - test:
-          requires:
-            - build
-      - push:
-          requires:
-            - test
+            sleep 20 # Augmenter le temps d'attente pour que le conteneur soit prêt
+            if ! curl http://localhost:8080/; then
+              echo "Failed to connect to the container. Logs:"
+              docker logs myapp_container
+              exit 1
+            fi
+      - run:
+          name: Push application Docker image
+          command: |
+            TAG=0.1.$CIRCLE_BUILD_NUM
+            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
+            docker push $DOCKERHUB_USERNAME/circleci-new-docker-example:$TAG
